---
title: "Homework 2"
author: "Biostats597E"
output: pdf_document
---

***
Download the homework 2 database **Homework2/homework2.sqlite** from course website.

***

You can print and turn in the homework when you come to class. It should contain all codes and partial output.

## Problem 1 - Customers Who Never Order

Suppose that a website contains two tables, the **customers** table and the **orders** table. Write a SQL query to find all customers who never order anything.

## Problem 2

A website is conducting online experiment using A/B testing. There are treatment group and control group in the experiment. There are many different metrics measuring how successful the treatment is over control group. The data is shown as **abtest**. 

Write SQL statement to find difference in  value between treatment group and control group (treatment - control) for each metric.

## Problem 3 - Full Join

Sqlite does not come with full join, however we can do full join using available joins and/or unions to achieve a full join.

Create a sample data as below.

```
create table one (X INT, Y INT);
insert into one values (1, 2), (2, 3), (3, 7);
create table two (X INT, Z INT);
insert into two values (2, 5), (3, 6), (4, 9)
```

Write a sql statement to full join table one and two on X.

Output should be (X, Y, Z): (1, 2, NULL), (2, 3, 5), (3, 7, 6), (4, NULL, 9)


